version: "3"
services:
  exdiary:
    image: liujl/exercisediary:0.1
    container_name: exdiary
    restart: unless-stopped
    ports:
      - 6638:8851
    volumes:
      - ./data:/data/ExerciseDiary
    environment:
      - TZ=Asia/Shanghai
      - AUTH=true
      - AUTH_EXPIRE=10M