name: GitHub-Packages-Docker

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ "main" ]  # 当推送到main分支时触发
    paths:
    - 'Dockerfile'
    - 'cmd/**'
    - 'internal/**'
  release:
    types: [published]  # 当发布新版本时触发

env:
  IMAGE_NAME: exercisediary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get version from file
        id: get_version
        run: |
          echo "VERSION=$(cat internal/web/public/version | grep VERSION= | cut -d= -f2)" >> $GITHUB_ENV
          echo "Version detected: ${{ env.VERSION }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ghcr.io/liujianglong/${{ env.IMAGE_NAME }}:latest
            ghcr.io/liujianglong/${{ env.IMAGE_NAME }}:${{ env.VERSION }}